<form class="form-horizontal" role="form">

<div class="row">
    <div class="col-xs-4">
        <div class="form-group">
            <label class="col-sm-4 control-label no-padding-right" for="form-field-1"> 招聘公司 </label>
            <div class="col-sm-8">
                <input type="text" id="form-field-1" placeholder=""  />
            </div>
        </div>
    </div>

    <div class="col-xs-4">
        <div class="form-group">
            <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 提供职位 </label>
            <div class="col-sm-9">
                <input type="text" id="form-field-1" placeholder=""  />
            </div>
        </div>
    </div>

    <div class="col-xs-4"></div>
</div>

 <div class="row">
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right" for="form-field-1"> 性别要求 </label>
                <div class="col-sm-8">
                    <select class="form-control" id="form-field-select-1">
                        <option value="3">不限</option>
                        <option value="1">男</option>
                        <option value="2">女</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 身高要求 </label>
                <div class="col-sm-9">
                    <input type="text" id="form-field-1" placeholder=""  />
                    <i class="icon-leaf green"></i>
                </div>
            </div>
        </div>
        <div class="col-xs-4"></div>
    </div>
<!--.row-->
    <div class="row">
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right" for="form-field-1"> 开始时间 </label>
                <div class="col-sm-8">
                            <div class="input-group">
                                <input class="form-control date-picker" id="id-date-picker-1" type="text" data-date-format="dd-mm-yyyy">
                                    <span class="input-group-addon">
                                        <i class="icon-calendar bigger-110"></i>
                                    </span>
                            </div>
                </div>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 结束时间 </label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input class="form-control date-picker" id="id-date-picker-1" type="text" data-date-format="dd-mm-yyyy">
                            <span class="input-group-addon">
                                <i class="icon-calendar bigger-110"></i>
                            </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-4"></div>
    </div>
 <!--#.row-->
  <!--.row-->
    <div class="row">
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right" for="form-field-1"> 工作时间 </label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input type="text" id="form-field-1" placeholder=""  />
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 结算方式 </label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <select class="form-control" id="form-field-select-1">
                            <option value="1">现金支付</option>
                            <option value="2">微信支付</option>
                            <option value="2">打卡支付</option>

                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-4"></div>
    </div>
    <!--#.row-->

    <!--.row-->
    <div class="row">
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right" for="form-field-1"> 工资待遇 </label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input type="text" id="form-field-1" placeholder="给多少RMB呢？"  />
                        <span class="label label-info arrowed-in-right arrowed">RMB</span>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1"> 招聘人数 </label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input type="text" id="form-field-1" placeholder="要多少人？"  />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-4"></div>
    </div>
    <!--#.row-->
    <!--.row-->
    <div class="row">
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right" for="form-field-1"> 联系人 </label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input type="text" id="form-field-1" placeholder=""  />
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-3 control-label no-padding-right" for="form-field-1">联系电话 </label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input type="text" id="form-field-1" placeholder="要多少人？"  />
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-4"></div>
    </div>
    <!--#.row-->

    <!--.row-->
    <div class="row">
        <div class="col-xs-4">
            <div class="form-group">
                <label class="col-sm-4 control-label no-padding-right" for="form-field-1"> 工作地点 </label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input type="text" id="form-field-1" placeholder=""  />
                    </div>

                </div>
            </div>
        </div>
        <div class="col-xs-8"></div>
    </div>
    <!--#.row-->


<div class="row">
<h4 class="header green clearfix">
         详细描述
        <span class="block pull-right">
            <small class="grey middle">选择编辑风格: &nbsp;</small>
            <span class="btn-toolbar inline middle no-margin">
                <span data-toggle="buttons" class="btn-group no-margin">
                    <label class="btn btn-sm btn-yellow">
                        1
                        <input type="radio" value="1" />
                    </label>

                    <label class="btn btn-sm btn-yellow active">
                        2
                        <input type="radio" value="2" />
                    </label>

                    <label class="btn btn-sm btn-yellow">
                        3
                        <input type="radio" value="3" />
                    </label>
                </span>
            </span>
        </span>
</h4>
<div class="wysiwyg-editor" id="editor1"></div>
</div>
<!--row-->
<div class="row">
    <button class="btn btn-info" type="button">
        <i class="icon-ok bigger-110"></i>
        确认无误,提交
    </button>

    &nbsp; &nbsp; &nbsp;
    <button class="btn" type="reset">
        <i class="icon-undo bigger-110"></i>
        写错了,重填
    </button>
<!--#/row-->
</div>
</form>
<!-- page specific plugin scripts -->


<script src='<?php echo $this->basePath() . '/js/jquery-2.0.3.min.js';?>'></script>
<script src="<?php echo $this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.ui.touch-punch.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/chosen.jquery.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/fuelux/fuelux.spinner.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/date-time/bootstrap-datepicker.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/date-time/bootstrap-timepicker.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/date-time/moment.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/date-time/daterangepicker.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/bootstrap-colorpicker.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.knob.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.autosize.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.inputlimiter.1.3.1.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.maskedinput.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/bootstrap-tag.min.js';?>"></script>


<!--编辑器-->
<script src="<?php echo $this->basePath() . '/js/markdown/markdown.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/markdown/bootstrap-markdown.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.hotkeys.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/bootstrap-wysiwyg.min.js';?>"></script>
<script src="<?php echo $this->basePath() . '/js/bootbox.min.js';?>"></script>
<!--#/编辑器-->
<script type="text/javascript">
jQuery(function($) {
    $('#id-disable-check').on('click', function() {
        var inp = $('#form-input-readonly').get(0);
        if(inp.hasAttribute('disabled')) {
            inp.setAttribute('readonly' , 'true');
            inp.removeAttribute('disabled');
            inp.value="This text field is readonly!";
        }
        else {
            inp.setAttribute('disabled' , 'disabled');
            inp.removeAttribute('readonly');
            inp.value="This text field is disabled!";
        }
    });


    $(".chosen-select").chosen();
    $('#chosen-multiple-style').on('click', function(e){
        var target = $(e.target).find('input[type=radio]');
        var which = parseInt(target.val());
        if(which == 2) $('#form-field-select-4').addClass('tag-input-style');
        else $('#form-field-select-4').removeClass('tag-input-style');
    });


    $('[data-rel=tooltip]').tooltip({container:'body'});
    $('[data-rel=popover]').popover({container:'body'});

    $('textarea[class*=autosize]').autosize({append: "\n"});
    $('textarea.limited').inputlimiter({
        remText: '%n character%s remaining...',
        limitText: 'max allowed : %n.'
    });

    $.mask.definitions['~']='[+-]';
    $('.input-mask-date').mask('99/99/9999');
    $('.input-mask-phone').mask('(999) 999-9999');
    $('.input-mask-eyescript').mask('~9.99 ~9.99 999');
    $(".input-mask-product").mask("a*-999-a999",{placeholder:" ",completed:function(){alert("You typed the following: "+this.val());}});
    $( "#input-size-slider" ).css('width','200px').slider({
        value:1,
        range: "min",
        min: 1,
        max: 8,
        step: 1,
        slide: function( event, ui ) {
            var sizing = ['', 'input-sm', 'input-lg', 'input-mini', 'input-small', 'input-medium', 'input-large', 'input-xlarge', 'input-xxlarge'];
            var val = parseInt(ui.value);
            $('#form-field-4').attr('class', sizing[val]).val('.'+sizing[val]);
        }
    });

    $( "#input-span-slider" ).slider({
        value:1,
        range: "min",
        min: 1,
        max: 12,
        step: 1,
        slide: function( event, ui ) {
            var val = parseInt(ui.value);
            $('#form-field-5').attr('class', 'col-xs-'+val).val('.col-xs-'+val);
        }
    });


    $( "#slider-range" ).css('height','200px').slider({
        orientation: "vertical",
        range: true,
        min: 0,
        max: 100,
        values: [ 17, 67 ],
        slide: function( event, ui ) {
            var val = ui.values[$(ui.handle).index()-1]+"";

            if(! ui.handle.firstChild ) {
                $(ui.handle).append("<div class='tooltip right in' style='display:none;left:16px;top:-6px;'><div class='tooltip-arrow'></div><div class='tooltip-inner'></div></div>");
            }
            $(ui.handle.firstChild).show().children().eq(1).text(val);
        }
    }).find('a').on('blur', function(){
        $(this.firstChild).hide();
    });

    $( "#slider-range-max" ).slider({
        range: "max",
        min: 1,
        max: 10,
        value: 2
    });

    $( "#eq > span" ).css({width:'90%', 'float':'left', margin:'15px'}).each(function() {
        // read initial values from markup and remove that
        var value = parseInt( $( this ).text(), 10 );
        $( this ).empty().slider({
            value: value,
            range: "min",
            animate: true

        });
    });


    $('#id-input-file-1 , #id-input-file-2').ace_file_input({
        no_file:'No File ...',
        btn_choose:'Choose',
        btn_change:'Change',
        droppable:false,
        onchange:null,
        thumbnail:false //| true | large
        //whitelist:'gif|png|jpg|jpeg'
        //blacklist:'exe|php'
        //onchange:''
        //
    });

    $('#id-input-file-3').ace_file_input({
        style:'well',
        btn_choose:'Drop files here or click to choose',
        btn_change:null,
        no_icon:'icon-cloud-upload',
        droppable:true,
        thumbnail:'small'//large | fit
        //,icon_remove:null//set null, to hide remove/reset button
        /**,before_change:function(files, dropped) {
						//Check an example below
						//or examples/file-upload.html
						return true;
					}*/
        /**,before_remove : function() {
						return true;
					}*/
        ,
        preview_error : function(filename, error_code) {
            //name of the file that failed
            //error_code values
            //1 = 'FILE_LOAD_FAILED',
            //2 = 'IMAGE_LOAD_FAILED',
            //3 = 'THUMBNAIL_FAILED'
            //alert(error_code);
        }

    }).on('change', function(){
        //console.log($(this).data('ace_input_files'));
        //console.log($(this).data('ace_input_method'));
    });


    //dynamically change allowed formats by changing before_change callback function
    $('#id-file-format').removeAttr('checked').on('change', function() {
        var before_change
        var btn_choose
        var no_icon
        if(this.checked) {
            btn_choose = "Drop images here or click to choose";
            no_icon = "icon-picture";
            before_change = function(files, dropped) {
                var allowed_files = [];
                for(var i = 0 ; i < files.length; i++) {
                    var file = files[i];
                    if(typeof file === "string") {
                        //IE8 and browsers that don't support File Object
                        if(! (/\.(jpe?g|png|gif|bmp)$/i).test(file) ) return false;
                    }
                    else {
                        var type = $.trim(file.type);
                        if( ( type.length > 0 && ! (/^image\/(jpe?g|png|gif|bmp)$/i).test(type) )
                            || ( type.length == 0 && ! (/\.(jpe?g|png|gif|bmp)$/i).test(file.name) )//for android's default browser which gives an empty string for file.type
                            ) continue;//not an image so don't keep this file
                    }

                    allowed_files.push(file);
                }
                if(allowed_files.length == 0) return false;

                return allowed_files;
            }
        }
        else {
            btn_choose = "Drop files here or click to choose";
            no_icon = "icon-cloud-upload";
            before_change = function(files, dropped) {
                return files;
            }
        }
        var file_input = $('#id-input-file-3');
        file_input.ace_file_input('update_settings', {'before_change':before_change, 'btn_choose': btn_choose, 'no_icon':no_icon})
        file_input.ace_file_input('reset_input');
    });




    $('#spinner1').ace_spinner({value:0,min:0,max:200,step:10, btn_up_class:'btn-info' , btn_down_class:'btn-info'})
        .on('change', function(){
            //alert(this.value)
        });
    $('#spinner2').ace_spinner({value:0,min:0,max:10000,step:100, touch_spinner: true, icon_up:'icon-caret-up', icon_down:'icon-caret-down'});
    $('#spinner3').ace_spinner({value:0,min:-100,max:100,step:10, on_sides: true, icon_up:'icon-plus smaller-75', icon_down:'icon-minus smaller-75', btn_up_class:'btn-success' , btn_down_class:'btn-danger'});



    $('.date-picker').datepicker({autoclose:true}).next().on(ace.click_event, function(){
        $(this).prev().focus();
    });
    $('input[name=date-range-picker]').daterangepicker().prev().on(ace.click_event, function(){
        $(this).next().focus();
    });

    $('#timepicker1').timepicker({
        minuteStep: 1,
        showSeconds: true,
        showMeridian: false
    }).next().on(ace.click_event, function(){
        $(this).prev().focus();
    });

    $('#colorpicker1').colorpicker();
    $('#simple-colorpicker-1').ace_colorpicker();


    $(".knob").knob();


    //we could just set the data-provide="tag" of the element inside HTML, but IE8 fails!
    var tag_input = $('#form-field-tags');
    if(! ( /msie\s*(8|7|6)/.test(navigator.userAgent.toLowerCase())) )
    {
        tag_input.tag(
            {
                placeholder:tag_input.attr('placeholder'),
                //enable typeahead by specifying the source array
                source: ace.variable_US_STATES,//defined in ace.js >> ace.enable_search_ahead
            }
        );
    }
    else {
        //display a textarea for old IE, because it doesn't support this plugin or another one I tried!
        tag_input.after('<textarea id="'+tag_input.attr('id')+'" name="'+tag_input.attr('name')+'" rows="3">'+tag_input.val()+'</textarea>').remove();
        //$('#form-field-tags').autosize({append: "\n"});
    }




    /////////
    $('#modal-form input[type=file]').ace_file_input({
        style:'well',
        btn_choose:'Drop files here or click to choose',
        btn_change:null,
        no_icon:'icon-cloud-upload',
        droppable:true,
        thumbnail:'large'
    })

    //chosen plugin inside a modal will have a zero width because the select element is originally hidden
    //and its width cannot be determined.
    //so we set the width after modal is show
    $('#modal-form').on('shown.bs.modal', function () {
        $(this).find('.chosen-container').each(function(){
            $(this).find('a:first-child').css('width' , '210px');
            $(this).find('.chosen-drop').css('width' , '210px');
            $(this).find('.chosen-search input').css('width' , '200px');
        });
    })
    /**
     //or you can activate the chosen plugin after modal is shown
     //this way select element becomes visible with dimensions and chosen works as expected
     $('#modal-form').on('shown', function () {
					$(this).find('.modal-chosen').chosen();
				})
     */

});
</script>
<script type="text/javascript">
    jQuery(function($){

        function showErrorAlert (reason, detail) {
            var msg='';
            if (reason==='unsupported-file-type') { msg = "Unsupported format " +detail; }
            else {
                console.log("error uploading file", reason, detail);
            }
            $('<div class="alert"> <button type="button" class="close" data-dismiss="alert">&times;</button>'+
                '<strong>File upload error</strong> '+msg+' </div>').prependTo('#alerts');
        }

        //$('#editor1').ace_wysiwyg();//this will create the default editor will all buttons

        //but we want to change a few buttons colors for the third style
        $('#editor1').ace_wysiwyg({
            toolbar:
                [
                    'font',
                    null,
                    'fontSize',
                    null,
                    {name:'bold', className:'btn-info'},
                    {name:'italic', className:'btn-info'},
                    {name:'strikethrough', className:'btn-info'},
                    {name:'underline', className:'btn-info'},
                    null,
                    {name:'insertunorderedlist', className:'btn-success'},
                    {name:'insertorderedlist', className:'btn-success'},
                    {name:'outdent', className:'btn-purple'},
                    {name:'indent', className:'btn-purple'},
                    null,
                    {name:'justifyleft', className:'btn-primary'},
                    {name:'justifycenter', className:'btn-primary'},
                    {name:'justifyright', className:'btn-primary'},
                    {name:'justifyfull', className:'btn-inverse'},
                    null,
                    {name:'createLink', className:'btn-pink'},
                    {name:'unlink', className:'btn-pink'},
                    null,
                    {name:'insertImage', className:'btn-success'},
                    null,
                    'foreColor',
                    null,
                    {name:'undo', className:'btn-grey'},
                    {name:'redo', className:'btn-grey'}
                ],
            'wysiwyg': {
                fileUploadError: showErrorAlert
            }
        }).prev().addClass('wysiwyg-style2');



        $('#editor2').css({'height':'200px'}).ace_wysiwyg({
            toolbar_place: function(toolbar) {
                return $(this).closest('.widget-box').find('.widget-header').prepend(toolbar).children(0).addClass('inline');
            },
            toolbar:
                [
                    'bold',
                    {name:'italic' , title:'Change Title!', icon: 'icon-leaf'},
                    'strikethrough',
                    null,
                    'insertunorderedlist',
                    'insertorderedlist',
                    null,
                    'justifyleft',
                    'justifycenter',
                    'justifyright'
                ],
            speech_button:false
        });


        $('[data-toggle="buttons"] .btn').on('click', function(e){
            var target = $(this).find('input[type=radio]');
            var which = parseInt(target.val());
            var toolbar = $('#editor1').prev().get(0);
            if(which == 1 || which == 2 || which == 3) {
                toolbar.className = toolbar.className.replace(/wysiwyg\-style(1|2)/g , '');
                if(which == 1) $(toolbar).addClass('wysiwyg-style1');
                else if(which == 2) $(toolbar).addClass('wysiwyg-style2');
            }
        });




        //Add Image Resize Functionality to Chrome and Safari
        //webkit browsers don't have image resize functionality when content is editable
        //so let's add something using jQuery UI resizable
        //another option would be opening a dialog for user to enter dimensions.
        if ( typeof jQuery.ui !== 'undefined' && /applewebkit/.test(navigator.userAgent.toLowerCase()) ) {

            var lastResizableImg = null;
            function destroyResizable() {
                if(lastResizableImg == null) return;
                lastResizableImg.resizable( "destroy" );
                lastResizableImg.removeData('resizable');
                lastResizableImg = null;
            }

            var enableImageResize = function() {
                $('.wysiwyg-editor')
                    .on('mousedown', function(e) {
                        var target = $(e.target);
                        if( e.target instanceof HTMLImageElement ) {
                            if( !target.data('resizable') ) {
                                target.resizable({
                                    aspectRatio: e.target.width / e.target.height,
                                });
                                target.data('resizable', true);

                                if( lastResizableImg != null ) {//disable previous resizable image
                                    lastResizableImg.resizable( "destroy" );
                                    lastResizableImg.removeData('resizable');
                                }
                                lastResizableImg = target;
                            }
                        }
                    })
                    .on('click', function(e) {
                        if( lastResizableImg != null && !(e.target instanceof HTMLImageElement) ) {
                            destroyResizable();
                        }
                    })
                    .on('keydown', function() {
                        destroyResizable();
                    });
            }

            enableImageResize();

            /**
             //or we can load the jQuery UI dynamically only if needed
             if (typeof jQuery.ui !== 'undefined') enableImageResize();
             else {//load jQuery UI if not loaded
			$.getScript($path_assets+"/js/jquery-ui-1.10.3.custom.min.js", function(data, textStatus, jqxhr) {
				if('ontouchend' in document) {//also load touch-punch for touch devices
					$.getScript($path_assets+"/js/jquery.ui.touch-punch.min.js", function(data, textStatus, jqxhr) {
						enableImageResize();
					});
				} else	enableImageResize();
			});
		}
             */
        }


    });
</script>
